image: archlinux
packages:
  - python
  - python-requests
sources:
  - https://github.com/bristol/events.git
secrets:
  - 831aaa6a-360e-42b0-98cc-49ae770789bf
tasks:
  - fetch: |
      cd events
      ./event-fetcher
  - deploy: |
      cd events
      git config user.email "louis@kragniz.eu"
      git config user.name "builds.sr.ht"
      git add -u
      git add events/
      git commit -m "Automated update via builds.sr.ht" -m "JOB_ID=${JOB_ID}" || true
      echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      git push git@github.com:bristol/events.git
triggers:
- to: builds <builds.sr.ht@kragniz.eu>
  action: email
  condition: failure
