image: archlinux
packages:
  - python
  - python-requests
sources:
  - https://github.com/bristol/events.git
secrets:
  - 831aaa6a-360e-42b0-98cc-49ae770789bf
tasks:
  - fetch: |
      cd events
      ./event-fetcher
  - deploy: |
      cd events
      git config user.email "louis@kragniz.eu"
      git config user.name "builds.sr.ht"
      git add -u
      git add events/
      git commit -m "Automated update via builds.sr.ht" -m "JOB_ID=${JOB_ID}" -m "Build log: https://builds.sr.ht/~kragniz/job/${JOB_ID}" || true
      echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' >> ~/.ssh/known_hosts
      git push git@github.com:bristol/events.git
triggers:
- to: builds <builds.sr.ht@kragniz.eu>
  action: email
  condition: failure
